spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/jpashop?&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # \uCD5C\uC801\uD654 \uC635\uC158
        show_sql: true
